// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CQRSGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "CQRSGenerator.f64a5c9f-7fb5-46f7-9255-f6c09dc94769";
        public const string Name = "CQRSGenerator";
        public const string Description = @"simplifies the process of working with the CQRS (Command Query Responsibility Segregation) design pattern in .NET projects. ";
        public const string Language = "en-US";
        public const string Version = "2.1";
        public const string Author = "Ahmed Abdel_Hafeez";
        public const string Tags = "";
    }
}
