// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CQRSGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "CQRSGenerator.f64a5c9f-7fb5-46f7-9255-f6c09dc94769";
        public const string Name = "CQRSGenerator";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Ahmed Abdel_Hafeez";
        public const string Tags = "";
    }
}
