// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CQRSGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CQRSGeneratorString = "ed20d321-d9de-4e0a-a3c6-853e1ad4afae";
        public static Guid CQRSGenerator = new Guid(CQRSGeneratorString);

        public const string GenerateCQRSString = "5d971c00-25b1-4e09-9548-e0ecc85511bb";
        public static Guid GenerateCQRS = new Guid(GenerateCQRSString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidMyCommand = 0x0100;
    }
}